// <auto-generated />
using System;
using KlinikaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KlinikaAPI.Migrations
{
    [DbContext(typeof(KlinikaDbContext))]
    [Migration("20250508131653_InitKlinikaDb")]
    partial class InitKlinikaDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("KlinikaAPI.Modele.Wizyta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZwierzeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZwierzeId");

                    b.ToTable("Wizyty");
                });

            modelBuilder.Entity("KlinikaAPI.Modele.Zwierze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Wiek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Zwierzeta");
                });

            modelBuilder.Entity("KlinikaAPI.Modele.Wizyta", b =>
                {
                    b.HasOne("KlinikaAPI.Modele.Zwierze", "Zwierze")
                        .WithMany("Wizyty")
                        .HasForeignKey("ZwierzeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zwierze");
                });

            modelBuilder.Entity("KlinikaAPI.Modele.Zwierze", b =>
                {
                    b.Navigation("Wizyty");
                });
#pragma warning restore 612, 618
        }
    }
}
